config/routes.rb
ThirdProject::Application.routes.draw do

  devise_for :users

  resources :ideas

  resources :tags

  resources :votes

  resources :comments

  resources :ideas
  get '/users', to: 'users#index'

  post '/save/idea', to: 'ideas#save'

  get '/users/:id', to: 'users#show'

  get '/index/tags', to: 'tags#index'

  get '/user/tags', to: 'tags#user_show'

  root :to => "welcome#index"

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :order => "created_at DESC"
  has_many :votes
  has_and_belongs_to_many :tags

  self.per_page = 10
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :ideas
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  has_many :ideas
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password, :bio, :github_URL, :portfolio_URL)}
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end


  #create a new comment and save it to an idea.
  def create
    @comment = Comment.create(content: params[:content])
    current_user.comments << @comment
    current_user.save

    idea = Idea.find(params[:ideaId])
    idea.comments << @comment
    idea.comments.order("created_at DESC")
    idea.save
    respond_to do |format|
      format.json {render json: @comment}
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  #all ideas
  def index
    # if current_user.nil?
    #   redirect_to new_user_session_path
    # else
        @ideas = Idea.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
        @user = current_user
        @user_vote_ids = [];
        @user.votes.each do |vote|
          @user_vote_ids << vote.idea_id
        end
    # end
  end


  #save new idea
  def save
    @idea = Idea.create(
    title: params[:title],
    content: params[:content],
    github_repo: params[:github_repo]
    )
    tag = Tag.where(name: params[:tag]).first_or_create
    @idea.tags << tag
    @idea.save
    current_user.ideas << @idea
    respond_to do |format|
      format.html
      format.js
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :content, :tag)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]


  def index
    @tag = Tag.where(name: params[:name]).order("created_at DESC")
    respond_to do |format|
      format.html
      format.js {}
    end
  end


  def user_show
    @tag = Tag.where(name: params[:name])
    @tagged_ideas = []
    @tag.first.ideas.each do |idea|
      if idea.user_id == params[:userId].to_i
        @tagged_ideas << idea
      end
    end
    respond_to do |format|
      format.html
      format.js {}
    end
  end



  private

    def set_tag
      @tag = Tag.find(params[:id])
    end


    def tag_params
      params[:tag]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_filter :authenticate_user!

  def index
    @user = current_user
    @user_ideas = @user.ideas.order("created_at DESC")
    @user_ideas.each do |idea|
      idea.comments.order("created_at DESC")
    end
    @user_vote_ids = [];
    @user.votes.each do |vote|
    @user_vote_ids << vote.idea_id
    end

  end

  def show
   @user = User.find(params[:id])
   @user_ideas = @user.ideas.order("created_at DESC")
  end



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # create a vote. add it to the idea fount from the vote button id
  def create
    vote = Vote.new
    @idea = Idea.find(params[:id])
    @idea.votes << vote
    @idea.save
    vote.save
    current_user.votes << vote
    current_user.save
    respond_to do |format|
      format.html
      format.js {}
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params[:vote]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user.nil?
        redirect_to new_user_session_path
    else
        redirect_to users_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/_idea.html.erb
<div class="row-fluid" id="idea-container">
  <div class="span12">

    <ul>
      <div id="<%= idea.id %>">
        <div class="span11" id="Idea-Box" style="border-bottom: 1px solid #EEE; margin-left: 1%;">

          <div class="span2">
           <a href="/users/<%=idea.user_id%>"><img src="http://farm6.staticflickr.com/5254/5488146741_b80f4b056a.jpg" class="img-polaroid"></a>
         </div>
         <div class="span8">

           <h3 ><%=idea.title%> </h3>
         </div>

          <div class="span8">
            <h4>  Tag: <%= idea.tags.first.name %></h4>
          </div>

         <div class="span3" >
           <h4> Votes: <span><%= idea.votes.count %></span>
            <% if @user_vote_ids.include?(idea.id) %>
            <% else %>
            <button id="vote_<%= idea.id %>" class="voteButton">Vote</button></h4>
            <% end %>

          </div>


        </div>
        <div class="span11">
          <div class="stats">

            <p><%=idea.content%></p>
            <small style="margin-left: 70%;"><cite>created at <%=idea.created_at.to_formatted_s(:short)%></cite></small>
          </div>
        </div>
        <div class="span9 offset2" id="idea-comments"style="background-color:white; border-radius:5px; border:none;">
          <ol>
            <% idea.comments.each do |comment| %>
            <% counter = 0 %>
            <div id="comment_<%= comment.id %>">
              <li><%=comment.content%></li>
              <ul>
                <li style="margin-left: 40%;"><small><cite class="usernameComment" id="comment.user.username" title="Source Title">--<a href="users/<%=comment.user.id%>"><%= comment.user.username %>, created this at <%=comment.created_at.to_formatted_s(:short)%></a></cite></small></li>
              </ul>
            </div>
            <% end %>
          </ol>
            <button id="indexCommentButton_<%= idea.id %>" class="indexCommentButton">See comments</button>
          <div id="commentBox">
            Add comment: <input id="mainComment<%= idea.id %>" type="text" name="comment" style="margin-top:1%;">
            <button id="<%= idea.id * 2 %>" class="mainCommentButton">submit</button>
          </div>
        </div>
      </div>
    </ul>
  </div>
</div>

app/views/ideas/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid">
        <div class="span7">
          <div class="ideas" >
            <%=render @ideas %>
          </div>
          <%= will_paginate @ideas %>
        </div>

        <div class="span4">
          <h3 style=" border-bottom: 1px solid #EEE; text-align:center;">Search by Tag</h3><input id="indexTagText" type="text" name="indexTag"><button class="indexTagSearchButton" id="indexTagSearchButton">Search</button>
          <div id="indexTagIdeas"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/ideas/index.js.erb
$('.ideas').append('<%= j render(@ideas) %>');
<% if @ideas.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@ideas) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/ideas/save.js.erb
var div = $('<div id="'+ <%=@idea.id%> +'"></div>').addClass("individual-idea-container"),
    li = '<h3><li>'+ '<%=@idea.title%>' +'</li></h3>',
    li2 = $('<li>'+ '<%=@idea.content%>' +'</li>').addClass("stats"),
    li3 = $('<li><li>').attr('id', 'idea-comments'),
    input = '<input id="comment" type="text" name="comment" placeholder="add a comment">',
    button = '<button data-id="'+ <%=@idea.id%> +'" class="commentButton">submit</button>',
    ideaForm = div.append(li).append(li2).append(li3).append(input).append(button).css("list-style-type", "none");

$('#'+<%=@idea.user_id%>).prepend(ideaForm);

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @idea.content %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @idea.tag %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>



<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid">
       <div id="bio-info">
          <div class="span3" style="background-color:grey; box-shadow: 10px 10px 5px #888888; border: 1px solid black; border-radius:10px;">
            <img src="http://farm6.staticflickr.com/5254/5488146741_b80f4b056a.jpg" class="img-polaroid">
            <h3>:github_URL</h3>
            <h3>:portfolio_URL</h3>
            <h3></h3>
            <p><h3>Bio</h3>Andouille flank brisket shankle meatball pork belly. Pancetta prosciutto chuck meatball, meatloaf</p>



          </div>
        </div>
        <div class="span1"></div>
        <div class="span7">
            <div class="row-fluid">
              <div class="span12" style="background-color:grey; box-shadow: 10px 10px 5px #888888; border: 1px solid black; border-radius:10px;">
                <a class="btn" href="#" style="float:right;">x</a>
                <h2 >Idea 1</h2>

                  <p style=" border-bottom: 1px solid #EEE;"></p>
                  <p>Filet mignon shoulder swine, kielbasa ribeye capicola sausage hamburger pork chop tri-tip meatball corned beef. Pork filet mignon biltong cow, turducken short loin tenderloin beef. Capicola shoulder pastrami prosciutto. Turkey pastrami pig tail sirloin. Prosciutto frankfurter pork chop, pork hamburger pancetta meatloaf. Pancetta rump tail shoulder salami doner. Frankfurter tri-tip jerky swine fatback brisket ribeye drumstick boudin.</p>
                  <div id="comment1">
                  <div class="row-fluid">
                      <div class="span8 offset4" style="background-color:white;">
                        <blockquote>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                          <small>Someone famous <cite title="Source Title">Source Title</cite></small>
                        </blockquote>
                      </div>
                  </div>
                  </div>
                  <div id="comment2">
                  <div class="row-fluid">
                      <div class="span8 offset4" style="background-color:white;">
                        <blockquote>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                          <small>Someone famous <cite title="Source Title">Source Title</cite></small>
                        </blockquote>
                      </div>
                  </div>
                  </div>
              </div>
            </div>
            <div class="row-fluid">
              <div class="span12"></div>
            </div>
            <div class="row-fluid">
              <div class="span12" style="background-color:grey; box-shadow: 10px 10px 5px #888888; border: 1px solid black; border-radius:10px;">
                <a class="btn" href="#" style="float:right;">x</a>
                <h2 >Idea 2</h2>

                <p style=" border-bottom: 1px solid #EEE;"></p>
                  <p>Filet mignon shoulder swine, kielbasa ribeye capicola sausage hamburger pork chop tri-tip meatball corned beef. Pork filet mignon biltong cow, turducken short loin tenderloin beef. Capicola shoulder pastrami prosciutto. Turkey pastrami pig tail sirloin. Prosciutto frankfurter pork chop, pork hamburger pancetta meatloaf. Pancetta rump tail shoulder salami doner. Frankfurter tri-tip jerky swine fatback brisket ribeye drumstick boudin.</p>
                   <div id="comment2">
                      <div class="row-fluid">
                          <div class="span8 offset4" style="background-color:white;">
                            <blockquote>
                              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                              <small>Someone famous <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                          </div>
                      </div>
                    </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>IdeaHub</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 0px;">
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <div class="container">

        <ul class="nav pull-right" style="font-size: 15px;
margin-top: 1.5%">

          <li><%=  (link_to 'Ideas', ideas_path ) %></li>
          <% if user_signed_in? %>
            <li>
            <%= (link_to 'Logout', destroy_user_session_path, :method => :delete) %>
            </li>
            <li>
              <%= link_to current_user.email, users_path %>
            </li>
          <% else %>
            <li>
            <%= (link_to('Login', new_user_session_path))  %>
            </li>
          <% end %>

        </ul>
      <h3 style="color:white"><%= image_tag("Bulb.png", :height => '32', :width => '32')  %> IdeaHub</h3>


    </div>
  </div>
 </div>
 <div id="main">
 </div>

<%= yield %>
<p></p>

</body>
</html>

app/views/tags/index.js.erb
$('#indexTagIdeas div').remove();
$('#indexTagIdeas a').remove();
<% @tag.first.ideas.each do |idea| %>
  var div = '<div class="tagSearchList"><ul><li class="tagIdeaTitle" id="ideaTitle_<%=idea.id%>">'+'<%= idea.title %>'+'</li></ul></div>';
  var li = '<li class="tagIdeaTitle" id="ideaTitle_<%=idea.id%>">'+'<%= idea.title %>'+'</li>';
  var p = '<p class="tagIdeaContent" id="ideaContent_<%=idea.id%>">'+'<%= idea.content %>'+'</p>'
  var a = '<a href="/users/<%=idea.user.id%>">created by <%=idea.user.username%></a>'
  $('#indexTagIdeas').append(div).append(p).append(a);
<% end %>

// $('.tagIdeaContent').hide();

$('.tagIdeaTitle').on('click', function(){
  var htmlId = this.id;
  console.log(htmlId);
  var id = htmlId.split('_')[1];
  console.log(id);
  $('#ideaContent_'+id).show();
});

app/views/tags/user_show.js.erb
<% @tagged_ideas.each do |idea| %>
  var div = '<div class="tagSearchList"><ul><li class="tagIdeaTitle" id="ideaTitle_<%=idea.id%>">'+'<%= idea.title %>'+'</li></ul></div>';
  var ul = '<ul></ul>';
  var li = '<li class="tagIdeaTitle" id="ideaTitle_<%=idea.id%>">'+'<%= idea.title %>'+'</li>';
  var p = '<p class="tagIdeaContent" id="ideaContent_<%=idea.id%>">'+'<%= idea.content %>'+'</p>'
  var a = '<a href="/users/<%=idea.user.id%>">created by <%=idea.user.username%></a>'
  $('#tagSearchBox').append(div).append(p).append(a);
<% end %>

app/views/users/_form.html.erb
<div class="row-fluid">
  <div class="span10" id="idea-container">
    <div id="profileIdeaHeader"><h3 style="margin-left: 35%">New Idea</h3></div>

    <div id="ideaInputForm" class="ideaInputForm" style="margin-left:20%;">
      Title:   <input id="title" type="text" name="title" style="margin-left: 9%;"></br>
      Content: <textarea rows="4" id="content" type="text" name="content" style = "margin-left:4%;" ></textarea></br>
      Tag:     <input id="tag" class="input-small" type="text" name="tag" style="margin-left: 10%;">
      Idea: <input id="idea" type="radio" name="idea">
      Project:<input id="project" type="radio" name="project">
      <button class="btn btn-small" id="submitButton">submit</button>
      <p id="project-input">Github URL:<input id="github-url" name="github-url" type="text" placeholder="http://"></p>
    </div>
  </div>
</div>

app/views/users/_idea.html.erb
<div class="fluid-row">
  <div class="span12">
    <div class="userIdeaClass">
      <ul id="<%= @user.id %>">
        <% @user_ideas.each do |idea| %>
        <div class="span12" id="idea-container">
          <div id="<%= idea.id %>" class="mainIdeaDiv">
           <div class="span11" style="border-bottom: 1px solid #EEE; margin-left:1%;" >
            <div class="span8">

              <h3 class="userIdeaTitle"><%=idea.title%></h3>

            </div>

             <div class="span8" id="tags-box">
             <h4>Tag: <%= idea.tags.first.name %></h4>
            </div>

            <div class="span3" id="vote-totals">
             <h4>Votes: <%= idea.votes.count %></h4>
           </div>


         </div>
         <div class="span11">
          <div class="stats">
            <p><%= idea.content %></p>
            <small style="margin-left: 70%;"><cite>created at <%=idea.created_at.to_formatted_s(:short)%></cite></small>
          </div>
        </div>
        <div clas="span11">
        <ul>
          <% idea.comments.each do |comment| %>

          <div class="span9 offset2" id="idea-comments" style="background-color:white; border:none; border-radius:5px;">
            <li><%=comment.content%></li>
            <ul>
              <li style="margin-left: 50%;"><small><cite class="usernameComment" id="comment.user.username" title="Source Title">--<a href="/users/<%=comment.user.id%>"><%= comment.user.username %></a>, created this at <%=comment.created_at.to_formatted_s(:short)%></cite></small></li>
            </ul>
          </div>
          <% end %>
          <input class="userTagSearchBox" id="profileCommentBox_<%= idea.id %>" type="text" name="comment" placeholder="add a comment">
          <button id="profileCommentButton_<%= idea.id %>" class="userCommentButton">submit</button>
          <button id="profileCommentButton_<%= idea.id %>" class="profileCommentButton">See comments</button></br>
          <div>
        </ul>
        </div>
      </div>
    </div>
    <% end %>
  </ul>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid">
          <div class="span3" id="bio" style=" border-radius:10px;">
           <img src="http://farm6.staticflickr.com/5254/5488146741_b80f4b056a.jpg" class="img-polaroid-profile">
           <div class="bio">
            <h3><%= @user.username %></h3>
            <p><%= @user.bio %></p>
          </div>

            Search Your Tags: </br>
            <input id="tagText" class="userTagSearchBox" type="text" name="tagSearchBox">
            <button class="tagSearchButton" id="tagSearchButton_<%= @user.id %>">Search</button>
             <div id="tagSearchBox"></div>

          </div>

          <div class="span1"></div>
        <div class="span7" >
            <div class="row-fluid">
              <div class="span12">

                  <%= render 'form' %>

              </div>
            </div>
        </div>
         <div class="span1"></div>

        <% if @user_ideas.empty?%>
        <%else%>
        <div class="span1"></div>
          <div class="span7">
            <div class="ideas" >

                    <%= render "idea" %>
            </div>
          </div>
           <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="row-fluid">
          <div class="span3" id="bio">
           <img src="http://farm6.staticflickr.com/5254/5488146741_b80f4b056a.jpg" class="img-polaroid-profile">
           <div class="bio">

            <h3><%= @user.username %></h3>

            <p><h5>Bio</h5><%= @user.bio %></p>
          </div>
            <div id="tagSearchBox">
            Search <%= @user.username %>'s Tags: </br>
            <input id="tagText" class="input-small" type="text" name="tagSearchBox">
            <button class="tagSearchButton" id="tagSearchButton_<%= @user.id %>">Search</button>
            </div>

          </div>

        <% if @user_ideas.empty?%>
        <%else%>
          <div class="span7">
                    <%= render 'idea' %>
          </div>
           <% end %>
      </div>
    </div>
  </div>
</div>

app/views/votes/create.js.erb
// $('#'+<%= @idea.id %>+' li span')[0].innerHTML = <%= @idea.votes.count %>;
$('#'+<%= @idea.id %>+' h4 span')[0].innerHTML = <%= @idea.votes.count %>;